# src/Showket/Bhat/Resources/config/routing.yml
ShowketBhatBundle_homepage:
    pattern:  /
    defaults: { _controller: ShowketBhatBundle:My:index }
    requirements:
        _method:  GET

ShowketBhatBundle_movies:
    pattern:  /movies
    defaults: { _controller: ShowketBhatBundle:My:movies }
    requirements:
        _method:  GET


ShowketBhatBundle_song:
    pattern:  /song
    defaults: { _controller: ShowketBhatBundle:My:song }
    requirements:
        _method:  GET
        
ShowketBhatBundle_register:
    pattern:  /register
    defaults: { _controller: ShowketBhatBundle:My:register }
    requirements:
        _method:  GET|POSt

ShowketBhatBundle_information:
    pattern:  /userinfo
    defaults: { _controller: ShowketBhatBundle:Userinfo:info }
    requirements:
        _method:  GET


ShowketBhatBundle_registeruser:
    pattern:  /register_user
    defaults: { _controller: ShowketBhatBundle:Userinfo:register }
    requirements:
        _method:  GET|POSt
